### ISSUE TITLE
How to set proxy for selenium chrome web driver

### ISSUE THREAD

**Issue by karunakaranvrv** [jarib/browsermob-proxy-rb#29]
@jarib @agile  I can able to create and set proxy for firefox profile but not on chrome.

I don't know which options i have to use for chrome to set proxy.

Am using the following code:-

For firefox:-

    require 'selenium/webdriver'
    require 'browsermob/proxy'
    
    server = BrowserMob::Proxy::Server.new("/path/to/downloads/browsermob-proxy/bin/browsermob-proxy") #=> #<BrowserMob::Proxy::Server:0x000001022c6ea8 ...>
    server.start
    
    proxy = server.create_proxy #=> #<BrowserMob::Proxy::Client:0x0000010224bdc0 ...>
    
    profile = Selenium::WebDriver::Firefox::Profile.new #=> #<Selenium::WebDriver::Firefox::Profile:0x000001022bf748 ...>
    profile.proxy = proxy.selenium_proxy
    
    driver = Selenium::WebDriver.for :firefox, :profile => profile
    
    proxy.new_har "google"
    driver.get "http://google.com"
    
    har = proxy.har #=> #<HAR::Archive:0x-27066c42d7e75fa6>
    har.entries.first.request.url #=> "http://google.com"
    har.save_to "/tmp/google.har"
    
    proxy.close
    driver.quit

For chrome:-

    require 'selenium/webdriver'
    require 'browsermob/proxy'
    
    server = BrowserMob::Proxy::Server.new("/path/to/downloads/browsermob-proxy/bin/browsermob-proxy") #=> #<BrowserMob::Proxy::Server:0x000001022c6ea8 ...>
    server.start
    
    proxy = server.create_proxy #=> #<BrowserMob::Proxy::Client:0x0000010224bdc0 ...>
    
    profile = Selenium::WebDriver::Chrome::Profile.new #=>
    profile.proxy = proxy.selenium_proxy
    
    driver = Selenium::WebDriver.for :chrome, :prefs => profile
    
    proxy.new_har "google"
    driver.get "http://google.com"
    
    har = proxy.har #=> #<HAR::Archive:0x-27066c42d7e75fa6>
    har.entries.first.request.url #=> "http://google.com"
    har.save_to "/tmp/google.har"
    
    proxy.close
    driver.quit

In chrome, errors throws on the following line

    profile.proxy = proxy.selenium_proxy

 Error:-   NoMethodError: undefined method `proxy=' for #<Selenium::WebDriver::Chrome::Profile:0x000000042d53a8>

How to set proxy on chrome driver profile ?

**Comment by jarib** [comment]
This is really a question for https://github.com/seleniumhq/selenium, but I think you can do this:

```ruby
Selenium::WebDriver.for :chrome, :desired_capabilities => { :proxy => proxy.selenium_proxy }
```

**Comment by karunakaranvrv** [comment]
@jarib Ya. Your answer works for me. Thanks
