### ISSUE TITLE
got RestClient::InternalServerError  when proxy.new_har 'new_page' 

### ISSUE THREAD

**Issue by tianlu1677** [jarib/browsermob-proxy-rb#38]
when I use `proxy.new_har 'new_page' `, I got 
```RestClient::InternalServerError: 500 Internal Server Error
from /Users/jacksontom/.rvm/gems/ruby-2.5.1/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
```
AND proxy detail is 
```
#<BrowserMob::Proxy::Client:0x00007f9c9731bbc8
 @host="localhost",
 @port=8081,
 @resource=#<RestClient::Resource:0x00007f9c9731bd30 @block=nil, @options={}, @url="http://localhost:8080/proxy/8081">>

```

```ruby
require 'selenium/webdriver'
require 'browsermob/proxy'

path = "/Users/jacksontom/Documents/browserup-proxy-1.2.1/bin/browserup-proxy"
server = BrowserMob::Proxy::Server.new(path) #=> #<BrowserMob::Proxy::Server:0x000001022c6ea8 ...>
server.start

proxy = server.create_proxy() #=> #<BrowserMob::Proxy::Client:0x0000010224bdc0 ...>

profile = Selenium::WebDriver::Firefox::Profile.new #=> #<Selenium::WebDriver::Firefox::Profile:0x000001022bf748 ...>
profile.proxy = proxy.selenium_proxy

driver = Selenium::WebDriver.for :firefox, :profile => profile

proxy.new_har "google"  # ERROR:
driver.get "https://baidu.com"

har = proxy.har #=> #<HAR::Archive:0x-27066c42d7e75fa6>
har.entries.first.request.url #=> "http://google.com"
har.save_to "/tmp/google.har"

proxy.close
driver.quit
```

**Comment by ericbeland** [comment]
I see basically the same error as you do if I run your code with other things running on the proxy ports. The error from the gem could be improved, but your code works well once I turn off the items running on the required ports (in my case, I killed Docker), or change it to use a different port.

`server = BrowserMob::Proxy::Server.new(path, log: true, port: 8089)`

**Comment by tianlu1677** [comment]
Port error I fixed.
When I use `proxy.new_har capture_content: true`, Then I got rest client 500 error.
I watch source code
```ruby

      def new_har(ref = nil, opts = {})
        if opts.empty? && ref.kind_of?(Hash)
          opts = ref
          ref = nil
        end

        params = {}

        params[:initialPageRef] = ref if ref
        params[:captureHeaders] = true if opts[:capture_headers]
        params[:captureContent] = true if opts[:capture_content]

        if opts[:capture_binary_content]
          params[:captureContent] = true
          params[:captureBinaryContent] = true
        end
        # binding.pry
        previous = @resource["har"].put params
        HAR::Archive.from_string(previous) unless previous.empty?
      end
```
and I tried 
`@resource["har"].put params.to_json`
but I got 
```
[20] pry(#<BrowserMob::Proxy::Client>)> @resource["har"].put (params.to_json)
Jun 20, 2019 3:49:14 PM com.google.sitebricks.binding.MvelRequestBinder validate
WARNING: Binding expression (request/form parameter) contained invalid characters: {"captureContent":true} (ignoring)
```
When I use `curl -X PUT -d 'captureContent=true&captureCookies=true&captureHeaders=true' http://localhost:8089/proxy/8090/har` no error. 
Sorry I do not know why  :(

**Comment by ericbeland** [comment]
The error you described will happen if you don't pass the Content-Type.  With curl, that needs -H 

"Content-Type: application/json"

This line looks wrong:

`proxy.new_har capture_content: true`

Your example omits the page ref, which has to be passed, and just passed the options, but the first argument becomes the pageref, so it is sending a pagename/pageref of 'capture_content: true' which the proxy may not like, and also, it never sets the option you're trying to pass. This looks better:

`proxy.new_har 'baidu', capture_content: true`

**Comment by tianlu1677** [comment]
Thanks. It's my mistake.  Because I used Java 9.  when I updated java 12 , everything is ok.

**Comment by ericbeland** [comment]
Interesting. We can check into that. Thanks!
